In [1]:
#1. What is a Python library? Why do we use Python libraries?
'''
1.) Numpy is python lib.
2.) NumPy stands for Numerical Python
3.)numpy is faster than list Becasue it is homogeneous
4.) it's computation is used in c++ so it is faster than list that's why we use it.'''

"\n1.) Numpy is python lib.\n2.) NumPy stands for Numerical Python\n3.)numpy is faster than list Becasue it is homogeneous\n4.) it's computation is used in c++ so it is faster than list that's why we use it."

In [2]:
#2. What is the ^ifference between Numpy array an^ List?

'''--List--
List are slower as compared to array
Numpy are homogenous so they store same type of data which inturns make them more efficient and faster.
also they have fix data type which makes them more relaible and less mermory comsuming and limit use of other type of data.
'''

'--List--\nList are slower as compared to array\nNumpy are homogenous so they store same type of data which inturns make them more efficient and faster.\nalso they have fix data type which makes them more relaible and less mermory comsuming and limit use of other type of data.\n'

In [7]:
#3. Fin^ the shape, size an^ ^imension of the following array?

'''[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''


'[[1, 2, 3, 4]\n\n[5, 6, 7, 8],\n\n[9, 10, 11, 12]]'

In [8]:
import numpy as np

In [18]:
arr =np.array([[1, 2, 3, 4], [5, 6, 7, 8],

[9, 10, 11, 12]])

In [19]:
arr.ndim # dimension

2

In [20]:
arr.size # Size

12

In [21]:
arr.shape # shape

(3, 4)

In [22]:
#4. Write python co^e to access the first row of the following array?
'''
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''


'\n[[1, 2, 3, 4]\n\n[5, 6, 7, 8],\n\n[9, 10, 11, 12]]'

In [24]:
arr8=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [30]:
arr8[0]

array([1, 2, 3, 4])

In [27]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
'''
[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

'\n[[1, 2, 3, 4]\n\n[5, 6, 7, 8],\n\n[9, 10, 11, 12]]'

In [42]:
arr9=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [43]:
arr9[2][3]

12

In [36]:
'''#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]'''

'#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?\n\n[[1, 2, 3, 4]\n\n[5, 6, 7, 8],\n\n[9, 10, 11, 12]]'

In [50]:
arr10=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])




In [51]:
odd_arr = arr10[arr10 % 2 != 0]

In [52]:
odd_arr

array([ 1,  3,  5,  7,  9, 11])

In [53]:
'''#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?'''

'#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?'

In [70]:
#arr12 = np.zeros((3,3))


In [71]:
#arr12

In [72]:
#arr13 = np.ones((3,3))

In [73]:
#arr13

In [75]:
arr15 = np.random.rand(3,3)

In [76]:
arr15

array([[0.25098939, 0.20762629, 0.31768853],
       [0.6850368 , 0.07071329, 0.50473963],
       [0.5219962 , 0.26540265, 0.77992875]])

In [82]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

#np.random.rand()-Create array with given size and also have uniform distribution and evenly discrtibuted

#np.random.randn()-normal distribution and uneven distribution

In [3]:
''' #9 Write a code  increase the  dim  of the f0llowing array'''
import numpy as np
arrr =[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [13]:
new_arr_1 = np.expand_dims(arrr, axis=1)


In [14]:
new_arr_1

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [54]:
#10. How to transpose the follwowing array in Numpy?

In [55]:
import numpy as np

arrr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [56]:
arr_tn =arrr.T

In [57]:
arr_tn 

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [60]:
'''11. PErform the  folowing operations'''

'11. PErform the  folowing operations'

In [61]:
Matrix1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

Matrix2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [62]:
#11.1 Index wise *

In [63]:
Matrix1*Matrix2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [64]:
#11.2 Dont know the answer

In [65]:
#11.3 Add both matrix

In [51]:
Matrix1 + Matrix2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [66]:
#11.4 Sub both matrix
Matrix2 - Matrix1


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
#11.4 Sub both matrix
Matrix2/Matrix1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
#12. Which fun in np can be  used to  swap the  byte order  of nay aray?

In [70]:
#byteswap() function can be used to swap thr order of any array except string.

In [74]:
#13.what is the significance of np.linalg.inv func

#.np.linalg.inv only works for square matrices. and inverse the matrics.

In [87]:

#14.#Can help you reshaping the the erray and with underlying elments

In [88]:

#15.Broadcasting in NumPy is a powerful mechanism that allows you to perform element-wise operations on arrays of different shapes.